In [2]:
import numpy as np


## DataTypes & Attributes

In [37]:
# Numpy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [39]:
a2=np.array([[1,2.0,3.3],[4,5,6.5]])
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [40]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape


(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [11]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
#Create a dataframe from numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2.Creating arrays

In [3]:
sample_array =np.array([1,2,3])
sample_array

array([1, 2, 3])

In [4]:
sample_array.dtype

dtype('int32')

In [5]:
ones=np.ones((2,3))

In [6]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
ones.dtype

dtype('float64')

In [8]:
type(ones)

numpy.ndarray

In [9]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [11]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[9, 0, 3, 9, 9],
       [8, 9, 2, 9, 7],
       [9, 4, 1, 6, 3]])

In [12]:
random_array.size

15

In [13]:
random_array.shape

(3, 5)

In [15]:
random_array2=np.random.random((5,3))
random_array2

array([[0.95861018, 0.72802417, 0.73171689],
       [0.38442947, 0.24663765, 0.27319844],
       [0.32741309, 0.80671665, 0.99864425],
       [0.20600499, 0.91137587, 0.86213035],
       [0.9459165 , 0.20766383, 0.44307137]])

In [16]:
random_array2.shape

(5, 3)

In [18]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.31605787, 0.38657162, 0.0891748 ],
       [0.21836727, 0.34432209, 0.48828753],
       [0.15654858, 0.05102095, 0.10571868],
       [0.37421751, 0.60927003, 0.59811684],
       [0.02538026, 0.09720385, 0.2607798 ]])

In [27]:
#Pseudo-random numbers
np.random.seed(seed=0)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [21]:
random_array_4.shape

(5, 3)

In [32]:
np.random.seed(seed=7)
random_array_5=np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [33]:
random_array_5=np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

### 3.Viewing arrays

In [34]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1

array([1, 2, 3])

In [42]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a1[0]

1

In [45]:
a2.shape

(2, 3)

In [46]:
a2[0]

array([1. , 2. , 3.3])

In [47]:
a3.shape

(2, 3, 3)

In [48]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [51]:
a2[1]

array([4. , 5. , 6.5])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [54]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [55]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [57]:
#Get the first 4 numbers of the innermost arrays
a4[:,:,:,:4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])